parameters:
  - name: deploymentEnvironment
    type: string
    default: prod
  - name: deploymentResources
    type: object
    default:
      - type: keyVault
        namePrefix: project00kv
        rGTN: Ops
        template: null
        suffix: abcdefghij
      - type: database
        namePrefix: project01sqls
        rGTN: Data
        template: null
        suffix: jihgfedcba
        databases:
          - name: database01db
            readers:            # Note: Readers also get the CONNECT grant, and the DLN {Env} DB Readers group will be added automatically.
              - name: database01mid
                includeSuffix: true
                environments: ['Dev', 'QA', 'Preprod', 'Prod']
            writers:            # Note: Writers also get the EXECUTE grant.
              - name: database01mid
                includeSuffix: true
                environments: ['QA', 'Preprod']
            admins:                 # Admins get the db_ddladmin role.
              - name: 'testemail@test.local'
                includeSuffix: false
                environments: ['Dev']
#          - name: database02db
#            readers:
#              - name: database02mid
#                environments: "Dev, QA, Preprod, Prod"
#            writers:
#              - name: database02mid
#                environments: "Dev, QA, Preprod, Prod"



variables:
  system.debug: true

jobs:
  - job: IterationAndAssignment
    displayName: "Iterate through each Supporting Resource and pull properties and suffixes via environment variables."
    steps:
      - checkout: none
      - bash: |
          echo "Number of resources: $numRes"
          echo "SQL Server for this run: $sqlServerName"
        env:
          numRes: ${{ length(parameters.deploymentResources) }}
          ${{ each res in parameters.deploymentResources }}:
              ${{ if eq(res.type, 'database') }}:
                sqlServerName: ${{res.namePrefix}}${{res.suffix}}

      - ${{ each res in parameters.deploymentResources }}:
          - bash: |
              echo "The resource we're working with is $namePrefix in the ProjectDev-$rGTN Resource Group."
              echo "It is a $type."
              echo ""; echo ""
              echo "Let's try to assign them as outputs."
              echo "##vso[task.setvariable variable=suffix;isOutput=true]$suffix"
            env:
              type: ${{res.type}}
              namePrefix: ${{res.namePrefix}}
              rGTN: ${{res.rGTN}}
              suffix: ${{res.suffix}}
            name: ${{res.type}}

  - job: TestIterationOutput
    displayName: "Test selectively deploying based on elements in an array."
    dependsOn: IterationAndAssignment
    variables:
      - ${{ each res in parameters.deploymentResources }}:
          - name: ${{res.type}}Suffix
            value: $[dependencies.IterationAndAssignment.outputs['${{res.type}}.suffix']]
    steps:
      - checkout: none
      - bash: |
          echo "Deployment Environment: ${{parameters.deploymentEnvironment}}"
#          echo "Test DB Environment check: ${{parameters.deploymentResources[1].databases[0].readers[0].environments}}"
#          echo "Does the DB need permissions for this environment? ${{ contains(parameters.deploymentResources[1].databases[0].readers[0].environments, parameters.deploymentEnvironment)}}"
      - ${{ each res in parameters.deploymentResources }}:
          - bash: |
              echo "Macro variable test for the suffix: $(${{res.type}}Suffix)"
              echo "Environment variable Macro test for the suffix: $suffix"
            env:
              suffix: $(${{res.type}}Suffix)
            displayName: Check variables for ${{res.namePrefix}}.
          - ${{ if eq(res.type, 'database') }}:
            - ${{each db in res.databases}}:
                - ${{ each reader in db.readers }}:
                    - ${{ if containsValue(reader.environments, parameters.deploymentEnvironment) }}:
                      - ${{ if eq(reader.includeSuffix, 'true') }}:
                        - bash: echo "Adding reader ${{reader.name}}$(databaseSuffix) to database ${{db.name}} in ${{parameters.deploymentEnvironment}}"
                      - ${{ else }}:
                        - bash: echo "Adding reader ${{reader.name}} to database ${{db.name}} in ${{parameters.deploymentEnvironment}}"
                - ${{ each writer in db.writers }}:
                    - ${{ if containsValue(writer.environments, parameters.deploymentEnvironment) }}:
                      - bash: echo "Adding writer ${{writer.name}} to database ${{db.name}} in ${{parameters.deploymentEnvironment}}"
                - ${{ each admin in db.admins }}:
                    - ${{ if containsValue(admin.environments, parameters.deploymentEnvironment) }}:
                      - bash: echo "Adding admin ${{admin.name}} to database ${{db.name}} in ${{parameters.deploymentEnvironment}}"