parameters:
  - name: supportingResources
    type: object
    default:
      - type: keyVault
        namePrefix: project00kv
        rGTN: Ops
        template: null
        suffix: abcdefghij
      - type: database
        namePrefix: project01sqls
        rGTN: Data
        template: null
        suffix: jihgfedcba

variables:
  system.debug: true

jobs:
  - job: IterationAndAssignment
    displayName: "Iterate through each Supporting Resource and pull via environment variables."
    steps:
      - checkout: none
      - bash: |
          echo "Number of resources: $numRes"
        env:
          numRes: ${{ length(parameters.supportingResources) }}
      - ${{ each res in parameters.supportingResources }}:
          - bash: |
              echo "The resource we're working with is $namePrefix in the ProjectDev-$rGTN Resource Group."
              echo "It is a $type."
              echo ""; echo ""
              echo "Let's try to assign them as outputs."
              echo "##vso[task.setvariable variable=suffix;isOutput=true]$suffix"
            env:
              type: ${{res.type}}
              namePrefix: ${{res.namePrefix}}
              rGTN: ${{res.rGTN}}
              suffix: ${{res.suffix}}
            name: ${{res.type}}

  - job: TestIterationOutput
    displayName: "See if we can dynamically name the steps under the job."
    dependsOn: IterationAndAssignment
    variables:
      - ${{ each res in parameters.supportingResources }}:
          - name: ${{res.type}}Suffix
            value: $[dependencies.IterationAndAssignment.outputs['${{res.type}}.suffix']]
    steps:
      - checkout: none
      - ${{ each res in parameters.supportingResources }}:
          - bash: |
              echo "Macro variable test for the suffix: $(${{res.type}}Suffix)"
              echo "Environment variable Macro test for the suffix: $suffix"
            env:
              suffix: $(${{res.type}}Suffix)
            displayName: Check variables for ${{res.namePrefix}}.