parameters:
  - name: deploymentEnvironment
    type: string
    default: Dev
  - name: deploymentResources
    type: object
    default:
      - type: keyVault
        namePrefix: project00kv
        rGTN: Ops
        template: null
        suffix: abcdefghij
      - type: database
        namePrefix: project01sqls
        rGTN: Data
        template: null
        suffix: jihgfedcba
        databases:
          - name: database01db
            readers:            # Note: Readers also get the CONNECT grant, and the DLN {Env} DB Readers group will be added automatically.
              - name: database01mid
                environments: "Dev, QA, Preprod, Prod"
            writers:            # Note: Writers also get the EXECUTE grant.
              - name: database01mid
                environments: "QA, Preprod"
          - name: database02db
            readers:
              - name: database02mid
                environments: "Dev, QA, Preprod, Prod"
            writers:
              - name: database02mid
                environments: "Dev, QA, Preprod, Prod"



variables:
  system.debug: true

jobs:
  - job: IterationAndAssignment
    displayName: "Iterate through each Supporting Resource and pull via environment variables."
    steps:
      - checkout: none
      - bash: |
          echo "Number of resources: $numRes"
          echo "SQL Server for this run: $sqlServerName"
        env:
          numRes: ${{ length(parameters.deploymentResources) }}
          ${{ each res in parameters.deploymentResources }}:
              ${{ if eq(res.type, 'database') }}:
                sqlServerName: ${{res.namePrefix}}${{res.suffix}}

      - ${{ each res in parameters.deploymentResources }}:
          - bash: |
              echo "The resource we're working with is $namePrefix in the ProjectDev-$rGTN Resource Group."
              echo "It is a $type."
              echo ""; echo ""
              echo "Let's try to assign them as outputs."
              echo "##vso[task.setvariable variable=suffix;isOutput=true]$suffix"
            env:
              type: ${{res.type}}
              namePrefix: ${{res.namePrefix}}
              rGTN: ${{res.rGTN}}
              suffix: ${{res.suffix}}
            name: ${{res.type}}

  - job: TestIterationOutput
    displayName: "See if we can dynamically name the steps under the job."
    dependsOn: IterationAndAssignment
    variables:
      - ${{ each res in parameters.deploymentResources }}:
          - name: ${{res.type}}Suffix
            value: $[dependencies.IterationAndAssignment.outputs['${{res.type}}.suffix']]
    steps:
      - checkout: none
      - ${{ each res in parameters.deploymentResources }}:
          - bash: |
              echo "Macro variable test for the suffix: $(${{res.type}}Suffix)"
              echo "Environment variable Macro test for the suffix: $suffix"
            env:
              suffix: $(${{res.type}}Suffix)
            displayName: Check variables for ${{res.namePrefix}}.
          - ${{ if eq('${{res.type}}', 'database') }}:
            - ${{each db in res.databases}}:
                - ${{ each reader in db.readers }}:
                    - ${{ if contains('${{reader.environments}}', '${{parameters.deploymentEnvironment}}') }}:
                      - bash: echo "Adding reader ${{reader}} to database ${{db.name}} in ${{parameters.deploymentEnvironment}}"
                    - ${{ else }}:
                      - bash: echo "Reader ${{reader}} not valid for ${{parameters.deploymentEnvironment}}"
                - ${{ each writer in db.writers }}:
                    - ${{ if contains('${{writer.environments}}', '${{parameters.deploymentEnvironment}}') }}:
                      - bash: echo "Adding writer ${{writer}} to database ${{db.name}} in ${{parameters.deploymentEnvironment}}"
                    - ${{ else }}:
                      - bash: echo "writer ${{writer}} not valid for ${{parameters.deploymentEnvironment}}"